[project]
name = "yolo"
version = "0.0.0"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.packages.find]
where = ["yolo"]

[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools",
]
