task: inference
source: demo/images/inference/image.png
fast_inference:  # onnx, trt or Empty
data:
  batch_size: 16
  shuffle: False
  pin_memory: True
  data_augment: {}
nms:
  min_confidence: 0.5
  min_iou: 0.5
save_predict: true