nc: 80

anchor:
  reg_max: 16
  strides: [8, 16, 32]

model:
  backbone:
  - Conv: 
      args: {out_channels: 32, kernel_size: 3}
  - Conv: 
      args: {out_channels: 64, kernel_size: 3, stride: 2}
  - Conv: 
      args: {out_channels: 64, kernel_size: 3}
  - Conv: 
      args: {out_channels: 128, kernel_size: 3, stride: 2}
  - Conv: 
      args: {out_channels: 64, kernel_size: 1}
  - Conv: 
      args: {out_channels: 64, kernel_size: 1}
      source: -2
  - Conv: 
      args: {out_channels: 64, kernel_size: 3}
  - Conv: 
      args: {out_channels: 64, kernel_size: 3}
  - Conv: 
      args: {out_channels: 64, kernel_size: 3}
  - Conv: 
      args: {out_channels: 64, kernel_size: 3}
  - Concat: 
      source: [-1, -3, -5, -6]
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
  - Pool: 
      args: {padding: 0}
  - Conv: 
      args: {out_channels: 128, kernel_size: 1}
  - Conv: 
      args: {out_channels: 128, kernel_size: 1}
      source: -3
  - Conv: 
      args: {out_channels: 128, kernel_size: 3, stride: 2}
  - Concat: 
      source: [-1, -3]
  - Conv: 
      args: {out_channels: 128, kernel_size: 1}
  - Conv: 
      args: {out_channels: 128, kernel_size: 1}
      source: -2
  - Conv: 
      args: {out_channels: 128, kernel_size: 3}
  - Conv: 
      args: {out_channels: 128, kernel_size: 3}
  - Conv: 
      args: {out_channels: 128, kernel_size: 3}
  - Conv: 
      args: {out_channels: 128, kernel_size: 3}
  - Concat: 
      source: [-1, -3, -5, -6]
      tags: 8x
  - Conv: 
      args: {out_channels: 512, kernel_size: 1}
  - Pool: 
      args: {padding: 0}
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
      source: -3
  - Conv: 
      args: {out_channels: 256, kernel_size: 3, stride: 2}
  - Concat: 
      source: [-1, -3]
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
      source: -2
  - Conv: 
      args: {out_channels: 256, kernel_size: 3}
  - Conv: 
      args: {out_channels: 256, kernel_size: 3}
  - Conv: 
      args: {out_channels: 256, kernel_size: 3}
  - Conv: 
      args: {out_channels: 256, kernel_size: 3}
  - Concat: 
      source: [-1, -3, -5, -6]
  - Conv: 
      args: {out_channels: 1024, kernel_size: 1}
      tags: 16x
  - Pool: 
      args: {padding: 0}
  - Conv: 
      args: {out_channels: 512, kernel_size: 1}
  - Conv: 
      args: {out_channels: 512, kernel_size: 1}
      source: -3
  - Conv: 
      args: {out_channels: 512, kernel_size: 3, stride: 2}
  - Concat: 
      source: [-1, -3]
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
      source: -2
  - Conv: 
      args: {out_channels: 256, kernel_size: 3}
  - Conv: 
      args: {out_channels: 256, kernel_size: 3}
  - Conv: 
      args: {out_channels: 256, kernel_size: 3}
  - Conv: 
      args: {out_channels: 256, kernel_size: 3}
  - Concat: 
      source: [-1, -3, -5, -6]
  - Conv: 
      args: {out_channels: 1024, kernel_size: 1}
      tags: 32x
  head:
  - SPPCSPConv: 
      args: {out_channels: 512}
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
  - UpSample: 
      args: {scale_factor: 2}
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
      source: 16x
  - Concat: 
      source: [-1, -2]
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
      source: -2
  - Conv: 
      args: {out_channels: 128, kernel_size: 3}
  - Conv: 
      args: {out_channels: 128, kernel_size: 3}
  - Conv: 
      args: {out_channels: 128, kernel_size: 3}
  - Conv: 
      args: {out_channels: 128, kernel_size: 3}
  - Concat: 
      source: [-1, -2, -3, -4, -5, -6]
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
  - Conv: 
      args: {out_channels: 128, kernel_size: 1}
  - UpSample: 
      args: {scale_factor: 2}
  - Conv: 
      args: {out_channels: 128, kernel_size: 1}
      source: 8x
  - Concat: 
      source: [-1, -2]
  - Conv: 
      args: {out_channels: 128, kernel_size: 1}
  - Conv: 
      args: {out_channels: 128, kernel_size: 1}
      source: -2
  - Conv: 
      args: {out_channels: 64, kernel_size: 3}
  - Conv: 
      args: {out_channels: 64, kernel_size: 3}
  - Conv: 
      args: {out_channels: 64, kernel_size: 3}
  - Conv: 
      args: {out_channels: 64, kernel_size: 3}
  - Concat: 
      source: [-1, -2, -3, -4, -5, -6]
  - Conv: 
      args: {out_channels: 128, kernel_size: 1}
  - Pool: 
      args: {padding: 0}
  - Conv: 
      args: {out_channels: 128, kernel_size: 1}
  - Conv: 
      args: {out_channels: 128, kernel_size: 1}
      source: -3
  - Conv: 
      args: {out_channels: 128, kernel_size: 3, stride: 2}
  - Concat: 
      source: [-1, -3, 63]
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
      source: -2
  - Conv: 
      args: {out_channels: 128, kernel_size: 3}
  - Conv: 
      args: {out_channels: 128, kernel_size: 3}
  - Conv: 
      args: {out_channels: 128, kernel_size: 3}
  - Conv: 
      args: {out_channels: 128, kernel_size: 3}
  - Concat: 
      source: [-1, -2, -3, -4, -5, -6]
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
  - Pool: 
      args: {padding: 0}
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
  - Conv: 
      args: {out_channels: 256, kernel_size: 1}
      source: -3
  - Conv: 
      args: {out_channels: 256, kernel_size: 3, stride: 2}
  - Concat: 
      source: [-1, -3, 51]
  - Conv: 
      args: {out_channels: 512, kernel_size: 1}
  - Conv: 
      args: {out_channels: 512, kernel_size: 1}
      source: -2
  - Conv: 
      args: {out_channels: 256, kernel_size: 3}
  - Conv: 
      args: {out_channels: 256, kernel_size: 3}
  - Conv: 
      args: {out_channels: 256, kernel_size: 3}
  - Conv: 
      args: {out_channels: 256, kernel_size: 3}
  - Concat: 
      source: [-1, -2, -3, -4, -5, -6]
  - Conv: 
      args: {out_channels: 512, kernel_size: 1}
  - RepConv: 
      args: {out_channels: 256}
      source: 75
  - RepConv: 
      args: {out_channels: 512}
      source: 88
  - RepConv: 
      args: {out_channels: 1024}
      source: 101
  - IDetect: 
      args:
        anchors:
            - [12,16, 19,36, 40,28]  # P3/8
            - [36,75, 76,55, 72,146]  # P4/16
            - [142,110, 192,243, 459,401]  # P5/32
      source: [102, 103, 104]
      output: True